services:
  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq
    ports:
    - "5672:5672"   # RabbitMQ server port
    - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest    # Default username
      RABBITMQ_DEFAULT_PASS: guest    # Default password
      RABBITMQ_DEFAULT_VHOST: "/"     # Default vhost
