spring:
  application:
    name: demo-spring-rabbit

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        concurrency: 1 # Minimum number of listener invoker threads.
        default-requeue-rejected: true # Whether rejected deliveries are re-queued by default.
        max-concurrency: 3
        prefetch: 250
        retry:
          enabled: true
          max-attempts: 4        # 4 total attempts
          initial-interval: 2s   # 2 seconds
          max-interval: 30s      # 30 seconds
          multiplier: 2          # doubles each time
    host: localhost #Default
    port: 5672 #Default
    username: guest #Default
    password: guest #Default
