spring:
  application:
    name: demo-spring-rabbit

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        concurrency: 1
        default-requeue-rejected: false
        max-concurrency: 3
        prefetch: 250
        retry:
          max-attempts: 3
          enabled: true
          initial-interval: 4s
          max-interval: 30s
          multiplier: 2
    host: localhost #Default
    port: 5672 #Default
    username: guest #Default
    password: guest #Default


custom-consumer:
  retry:
    enabled: true
    max-attempts: 5
    initial-interval: 5s
    max-interval: 40s
    multiplier: 3
